// Package a2a adapts the official A2A protocol types and client from
// github.com/a2aproject/a2a-go (v0.3.x, the JSON/spec-compatible line) for use
// in the Unibase AIP SDK. The core protocol types are aliased directly from
// a2a-go so the SDK stays wire-compatible with the Google A2A ecosystem; this
// file adds the small constructor/accessor helpers the SDK relies on.
package a2a

import a2ago "github.com/a2aproject/a2a-go/a2a"

// Core protocol types, aliased from a2a-go.
type (
	// Message is a single message in a user/agent conversation.
	Message = a2ago.Message
	// Task is a stateful operation between a client and an agent.
	Task = a2ago.Task
	// TaskStatus is the status of a task at a point in time.
	TaskStatus = a2ago.TaskStatus
	// Artifact is a resource generated by an agent during a task.
	Artifact = a2ago.Artifact
	// Part is a discriminated content part (text, data, or file).
	Part = a2ago.Part
	// TextPart is a text content part.
	TextPart = a2ago.TextPart
	// DataPart is a structured-data content part.
	DataPart = a2ago.DataPart
	// ContentParts is an ordered list of parts.
	ContentParts = a2ago.ContentParts
	// Role identifies the sender of a message.
	Role = a2ago.MessageRole
	// TaskState enumerates the lifecycle states of a task.
	TaskState = a2ago.TaskState
	// TaskID is a task identifier.
	TaskID = a2ago.TaskID
	// TaskStatusUpdateEvent notifies of a change in a task's status.
	TaskStatusUpdateEvent = a2ago.TaskStatusUpdateEvent
	// TaskArtifactUpdateEvent notifies that an artifact was generated/updated.
	TaskArtifactUpdateEvent = a2ago.TaskArtifactUpdateEvent
	// Event is the interface implemented by streamable A2A events.
	Event = a2ago.Event
)

// Message roles.
const (
	RoleUser  = a2ago.MessageRoleUser
	RoleAgent = a2ago.MessageRoleAgent
)

// Task lifecycle states.
const (
	TaskStateSubmitted     = a2ago.TaskStateSubmitted
	TaskStateWorking       = a2ago.TaskStateWorking
	TaskStateInputRequired = a2ago.TaskStateInputRequired
	TaskStateCompleted     = a2ago.TaskStateCompleted
	TaskStateCanceled      = a2ago.TaskStateCanceled
	TaskStateFailed        = a2ago.TaskStateFailed
	TaskStateRejected      = a2ago.TaskStateRejected
	TaskStateAuthRequired  = a2ago.TaskStateAuthRequired
	TaskStateUnknown       = a2ago.TaskStateUnknown
)

// NewTextPart builds a text part.
func NewTextPart(text string) Part { return a2ago.TextPart{Text: text} }

// NewDataPart builds a structured-data part.
func NewDataPart(data map[string]any) Part { return a2ago.DataPart{Data: data} }

// NewMessage builds a Message with the given role, id, and a single text part.
// An empty id is replaced with a generated message id.
func NewMessage(role Role, messageID, text string) *Message {
	if messageID == "" {
		messageID = a2ago.NewMessageID()
	}
	return &Message{ID: messageID, Role: role, Parts: ContentParts{NewTextPart(text)}}
}

// NewMessageID generates a new random message identifier.
func NewMessageID() string { return a2ago.NewMessageID() }

// GetMessageText concatenates the text of all text parts in a message.
func GetMessageText(m *Message) string {
	if m == nil {
		return ""
	}
	var out string
	for _, p := range m.Parts {
		if tp, ok := p.(a2ago.TextPart); ok {
			out += tp.Text
		}
	}
	return out
}

// GetMessageData returns the data of the first data part, if any.
func GetMessageData(m *Message) map[string]any {
	if m == nil {
		return nil
	}
	for _, p := range m.Parts {
		if dp, ok := p.(a2ago.DataPart); ok {
			return dp.Data
		}
	}
	return nil
}

// PartText returns the text of a part when it is a text part.
func PartText(p Part) (string, bool) {
	tp, ok := p.(a2ago.TextPart)
	return tp.Text, ok
}

// PartData returns the data of a part when it is a data part.
func PartData(p Part) (map[string]any, bool) {
	dp, ok := p.(a2ago.DataPart)
	return dp.Data, ok
}
